
nginx_conf_dir: /etc/nginx
nginx_sites_dir: "{{ nginx_conf_dir }}/sites-enabled"

rstudio_version: 1.0.143
rstudio_package_url: "http://download2.rstudio.org/rstudio-server-{{ rstudio_version }}-amd64.deb"
rstudio_local_tmp_package: /tmp/rstudio-server.deb

modules_home: /usr/share/modules/modulefiles

jupyterhub_location: /jupyter/
jupyterhub_port: 9510
# jupyter dependent versions
jupyterhub_version: 0.7.2
configurable_http_proxy_version: 1.2.0
ipython_notebook_version: 5.0.0
matplotlib_version: 1.5.1
scipy_version: 0.17.1
pandas_version: 0.18.1

new_user: researcher
use_ubuntu_password: "yes"
homedir_path: /mnt/galaxy/home
user_shell: /bin/bash

cloudman_config_file: /opt/cloudman/boot/userData.yaml

gvl_cmdlineutils_version: "4.1.0"
gvl_cmdlineutils_build_date: "{{ ansible_date_time.iso8601 }}"
gvl_install_path: /opt/gvl