- name: Create JupyterHub configuration directory
  file:
    path: "/etc/jupyterhub"
    state: "directory"
    mode: "0755"

- name: Write out the JupyterHub config
  template: src=jupyterhub_config.py dest="/etc/jupyterhub/jupyterhub_config.py"

- name: Configure JupyterHub to run an upstart job
  file: src=jupyterhub.conf dest=/etc/init/jupyterhub.conf

- name: Start the JupyterHub service
  service: name=jupyterhub state=started

