- name: Make sure apt up to date
  apt: update_cache=yes
  sudo_user: root

- name: "Install JupyterHub required packages"
  apt: name={{ item }}
  with_items:
    - npm
    - nodejs-legacy
    - python3-pip
  sudo: yes
  sudo_user: root

- name: "Install JupyterHub node packages"
  npm: name=configurable-http-proxy global=yes
  sudo: yes
  sudo_user: root

- name: "Install JupyterHub node packages"
  pip: name={{ item }} executable=pip3 state=latest
  with_items:
    - ipython[notebook]
    - jupyterhub
  sudo: yes
  sudo_user: root

- name: Make sure Python matplotlib installed
  apt: name=python-matplotlib
  sudo_user: root

- name: Set up JupyterHub NGINX redirect
  template: src=jupyterhub.locations dest="{{ nginx_sites_dir }}"
  sudo_user: root

- name: Reload NGINX
  service: name=nginx state=reloaded
  sudo_user: root
