- name: Make sure apt up to date
  apt: update_cache=yes
  become: yes
  ignore_errors: yes

- name: "Get and install latest pip3"
  apt:
    name: python3-pip
    state: latest
  become: yes

- name: "Install JupyterHub required packages"
  apt: 
    name: ['npm', 'nodejs-legacy', 'python3-pip', 'libfreetype6-dev']
  become: yes

- name: "Update node packages"
  npm:
    name: n
    global: yes
  become: yes

- name: "Install latest stable node"
  command: "n stable"
  become: yes

- name: "Install ipython"
  pip: 
    name: ipython
    state: present 
    version: "{{ ipython_version }}"
    executable: /usr/bin/pip3
  become: yes

- name: "Install ipykernel"
  pip: 
    name: ipykernel 
    state: present 
    version: "{{ ipython_kernel_version }}"
    executable: /usr/bin/pip3
  become: yes

- name: "Install JupyterHub node packages"
  npm: 
    name: configurable-http-proxy 
    global: yes 
    version: "{{ configurable_http_proxy_version }}"
  become: yes

- name: "Install JupyterHub dependencies"
  pip: 
    name: "{{ item.name }}"
    state: present 
    version: "{{ item.version }}"
    executable: /usr/bin/pip3
  with_items:
    - { name: "notebook", version: "{{ ipython_notebook_version }}" }
    - { name: "matplotlib", version: "{{ matplotlib_version }}" }
    - { name: "scipy", version: "{{ scipy_version }}" }
    - { name: "pandas", version: "{{ pandas_version }}" }
    - { name: "jupyterhub", version: "{{ jupyterhub_version }}" }
  become: yes

- name: Set up JupyterHub NGINX redirect
  template: 
    src: jupyterhub.locations 
    dest: "{{ nginx_sites_dir }}"
  become: yes

- name: Reload NGINX
  service: 
    name: nginx 
    state: reloaded
  become: yes

- name: Create JupyterHub configuration directory
  file:
    path: "/etc/jupyterhub"
    state: "directory"
    mode: "0755"
  become: yes

- name: Write out the JupyterHub config
  template: 
    src: jupyterhub_config.py
    dest: "/etc/jupyterhub/jupyterhub_config.py"
  become: yes

- name: Configure logrotate for Jupterhub
  template:
    src: jupyterhub.logrotate
    dest: /etc/logrotate.d/jupyterhub
  become: yes

#- name: Install JupyterHub Python2 kernel
#  command: python2 -m IPython kernelspec install-self
#  become: yes
#
- name: Configure JupyterHub to run as a systemd service
  copy: 
    src: jupyterhub.service 
    dest: /etc/systemd/system/jupyterhub.service
  become: yes

- name: Start the JupyterHub service
  service: 
    name: jupyterhub 
    state: started 
    enabled: yes
  become: yes
