- name: Make sure apt up to date
  apt: update_cache=yes
  sudo_user: root

- name: "Install JupyterHub required packages"
  apt: name={{ item }}
  with_items:
    - npm
    - nodejs-legacy
    - python3-pip
    - libfreetype6-dev # for matplotlib
  sudo: yes
  sudo_user: root

- name: "Install JupyterHub node packages"
  npm: name=configurable-http-proxy global=yes version="{{ configurable_http_proxy_version }}"
  sudo: yes
  sudo_user: root

- name: "Install JupyterHub python packages"
  pip: name={{ item.name }} executable=pip3 state=present version={{ item.version }}
  with_items:
    - { name: "ipython[notebook]", version: "{{ ipython_notebook_version }}" }
    - { name: "git+git://github.com/jupyter/jupyterhub.git@{{ jupyterhub_commit }}", version: }
    - { name: "matplotlib", version: "{{ matplotlib_version }}" }
    - { name: "scipy", version: "{{ scipy_version }}" }
    - { name: "pandas", version: "{{ pandas_version }}" }
  sudo: yes
  sudo_user: root

- name: Set up JupyterHub NGINX redirect
  template: src=jupyterhub.locations dest="{{ nginx_sites_dir }}"
  sudo_user: root

- name: Reload NGINX
  service: name=nginx state=reloaded
  sudo_user: root

- name: Create JupyterHub configuration directory
  file:
    path: "/etc/jupyterhub"
    state: "directory"
    mode: "0755"

- name: Write out the JupyterHub config
  template: src=jupyterhub_config.py dest="/etc/jupyterhub/jupyterhub_config.py"

- name: Configure JupyterHub to run an upstart job
  copy: src=jupyterhub.conf dest=/etc/init/jupyterhub.conf

- name: Start the JupyterHub service
  service: name=jupyterhub state=started
