- include: install_libraries.yml

- include: create_toolshed_modules.yml
  tags:
      - toolshed_modules

- include: install_rstudio_server.yml

- include: install_jupyterhub.yml

- include: setup_new_user.yml
  tags:
      - setup_user

- include: configure_gvl_settings.yml
