- name: Create public_html directory
  file: name=/home/{{ new_user }}/public_html state=directory owner={{ new_user }} group={{ new_user }} mode=755
  become_user: "{{ new_user }}"

- name: Set up public_html redirect
  template: src=public_html.locations dest="{{ nginx_sites_dir }}/public_html_{{ new_user }}.locations"
  become_user: root

- name: Restart NGINX
  service: name=nginx state=restarted
  become_user: root
